### ISSUE TITLE
ATLauncher Issue

### ISSUE THREAD

**Issue by NordicGamerFE** [NordicGamerFE/Ocean-Outlast#17]
hi to all im new here , i trie to donwload on the atl launcher but i have this error , did anyone had the same error and could fix ?

[14/7/2020 22:17:51 PM] java.lang.NullPointerException
	at com.atlauncher.data.minecraft.loaders.forge.ForgeLoader.getMainClass(ForgeLoader.java:179)
	at com.atlauncher.workers.InstanceInstaller.determineMainClass(InstanceInstaller.java:590)
	at com.atlauncher.workers.InstanceInstaller.install(InstanceInstaller.java:416)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:205)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
tkx very much in advance

_Originally posted by @Elsewere in https://github.com/NordicGamerFE/Ocean-Outlast/issues/14#issuecomment-658431928_

**Comment by NordicGamerFE** [comment]
Send the entire log from you start ATLauncher until you get this issue

**Comment by Elsewere** [comment]
[34WzFvsJ.txt](https://github.com/NordicGamerFE/Ocean-Outlast/files/4943086/34WzFvsJ.txt)

**Comment by NordicGamerFE** [comment]
Update ATLauncher

**Comment by Elsewere** [comment]
ok , tkx i'll give you feedback in a few minutes
