### ISSUE TITLE
Server crash when I join

### ISSUE THREAD

**Issue by JSteenberg** [NordicGamerFE/Ocean-Outlast#41]
Version: ExpertV51
 
Description:
When I join the game the server crash, I just flew around loading some chucks, and then it crashes and does that every time I join.. Any idea ?

Crash Report:
19:03:40] [Server thread/INFO] [minecraft/DedicatedServer]: Steenberg joined the game
[19:03:41] [Server thread/INFO] [buildinggadgets]: Sending SyncedConfig to freshly logged in player Steenberg.
[19:03:41] [Server thread/INFO] [cqrepoured]: Loading player reputation...
Exception in thread "Thread-1699" [19:03:41] [Server thread/INFO] [Waila]: Player EntityPlayerMP['Steenberg'/619, l='world', x=1366.62, y=63.72, z=941.05] connected. Sending ping
[19:03:41] [Thread-1699/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NullPointerException
[19:03:41] [Thread-1699/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at com.teamcqr.chocolatequestrepoured.factions.FactionRegistry$1$1.accept(FactionRegistry.java:389)
[19:03:41] [Thread-1699/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at com.teamcqr.chocolatequestrepoured.factions.FactionRegistry$1$1.accept(FactionRegistry.java:381)
[19:03:41] [Thread-1699/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.lang.Iterable.forEach(Unknown Source)
[19:03:41] [Thread-1699/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at com.teamcqr.chocolatequestrepoured.factions.FactionRegistry$1.run(FactionRegistry.java:381)
[19:03:41] [Thread-1699/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.lang.Thread.run(Unknown Source)
[19:03:41] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[19:03:41] [Server thread/INFO] [Actually Additions]: Sending Player Data to player Steenberg with UUID 9656546d-088a-4b8b-877a-08bcfa87a607.
[19:03:42] [Server thread/INFO] [Mekanism]: Sent config to 'Steenberg.'
[19:03:46] [Server thread/WARN] [minecraft/EntityDataManager]: defineId called for: class net.daveyx0.multimob.entity.EntityMMBird from class net.daveyx0.multimob.entity.EntityMMFlyingMob
[19:04:42] [Server Watchdog/FATAL] [minecraft/ServerHangWatchdog]: A single server tick took 60.00 seconds (should be max 0.05)
[19:04:42] [Server Watchdog/FATAL] [minecraft/ServerHangWatchdog]: Considering it to be crashed, server will forcibly shutdown.
[19:04:42] [Server Watchdog/INFO] [packcrashinfo]: No manfiest present, attempting to load the minecraftinstance.json file.
[19:04:42] [Server Watchdog/ERROR] [packcrashinfo]: No manifest or minecraftinstance.json present
[19:04:42] [Server Watchdog/ERROR] [minecraft/ServerHangWatchdog]: This crash report has been saved to: C:\Users\jonas\Desktop\Ny mappe\servers\OceanOutlast\.\crash-reports\crash-2020-08-31_19.04.42-server.txt
[19:04:42] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
[19:04:42] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Saving players
Did you add additional mods?
[yes/no]
[if yes, what mods and what versions?]

**Comment by NordicGamerFE** [comment]
Please upload the crash log

**Comment by JSteenberg** [comment]
[crash-2020-08-31_19.04.42-server.txt](https://github.com/NordicGamerFE/Ocean-Outlast/files/5151923/crash-2020-08-31_19.04.42-server.txt)

**Comment by JSteenberg** [comment]
I just tried to reset from backup, it worked but then I flew the other way, and after 1000 blocks it crashed.

**Comment by NordicGamerFE** [comment]
How much ram is the server running?

**Comment by JSteenberg** [comment]
11G

**Comment by NordicGamerFE** [comment]
What java version does it run?

**Comment by JSteenberg** [comment]
src="https://user-images.githubusercontent.com/60323164/92208529-af788f00-ee8b-11ea-8a39-dcf944e0ed77.png">

**Comment by JSteenberg** [comment]
V8 update 261 (build 1.8.0_261-b12)

**Comment by NordicGamerFE** [comment]
Did v.52 fix it for you?

**Comment by JSteenberg** [comment]
YEP! now it just lags loading many chucks (which is fine) :) But it did not solve the skystone sieve problem..
