### ISSUE TITLE
World gen issue log

### ISSUE THREAD

**Issue by NordicGamerFE** [NordicGamerFE/Ocean-Outlast#45]
```
Unable to configure ModInfo
java.lang.IncompatibleClassChangeError
	at net.ilexiconn.llibrary.client.lang.LanguageHandler.addRemoteLocalizations(LanguageHandler.java:91)
	at net.ilexiconn.llibrary.LLibrary$CoreAPIHandler.addRemoteLocalizations(LLibrary.java:111)
	at net.ilexiconn.llibrary.server.core.patcher.LLibraryHooks.addRemoteLocalizations(LLibraryHooks.java:31)
	at net.minecraft.client.resources.Locale.loadLocaleDataFiles(Locale.java:32)
	at modinfo.ModInfo.getLocale(ModInfo.java:271)
	at modinfo.ModInfo.<init>(ModInfo.java:53)
	at journeymap.client.JourneymapClient.startMapping(JourneymapClient.java:531)
	at journeymap.client.task.main.MappingMonitorTask.perform(MappingMonitorTask.java:72)
	at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:84)
	at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:639)
	at journeymap.client.forge.event.StateTickHandler.onClientTick(StateTickHandler.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3529_StateTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Did you add additional mods?
[yes/no]
[if yes, what mods and what versions?]

**Comment by NordicGamerFE** [comment]
Seems to be fixed in V.52
