### ISSUE TITLE
Minotaurus is invisible and causes a large amount of log spam

### ISSUE THREAD

**Issue by cenodis** [NordicGamerFE/Ocean-Outlast#5]
The following Stacktrace is printed each frame when the game attempts to render a Minotaurus. The Minotaurus does not get rendered properly due to this error and is invisible in game. In addition the constant log spam can take up a rather large amount of disk space.

```
[19:21:52] [Client thread/ERROR] [minecraft/RenderLivingBase]: Couldn't render entity
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at gaia.entity.monster.EntityGaiaMinotaurus.isSwingingArms(EntityGaiaMinotaurus.java:229) ~[EntityGaiaMinotaurus.class:?]
	at gaia.model.ModelGaiaMinotaurus.setRotationAngles(ModelGaiaMinotaurus.java:241) ~[ModelGaiaMinotaurus.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.doRender(RenderLivingBase.java:146) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.doRender(SourceFile:41) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.doRender(SourceFile:16) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:384) [bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:368) [bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.redirect$zbo000$renderEntityStatic(RenderGlobal.java:2637) [buy.class:?]
	at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:628) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1347) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by NordicGamerFE** [comment]
I dont have this issue on my side i gonna try something else when i upload to twitch this time closed until further notice
